[package]
name = "devctl"
version = "0.1.0"
authors = ["zerosign <r1nlx0@gmail.com>"]
edition = "2018"

[dependencies]
serde-lexpr = "0.1.1"
combine = "4.0.0-beta.1"

[build-dependencies]
built = "0.3"
